# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

#type: sphinx
python:
  version: 3.6

#requirements_file: requirements-docs.txt